// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: contacts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addContact = `-- name: AddContact :exec
INSERT INTO contacts (user_id, contact_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddContactParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	ContactID pgtype.UUID `json:"contact_id"`
}

func (q *Queries) AddContact(ctx context.Context, arg AddContactParams) error {
	_, err := q.db.Exec(ctx, addContact, arg.UserID, arg.ContactID)
	return err
}

const getContacts = `-- name: GetContacts :many
SELECT 
    u.id AS contact_id,
    u.first_name,
    u.second_name,
    u.phone_number,
    u.image
FROM contacts c 
JOIN users u ON u.id = c.contact_id
WHERE c.user_id = $1
ORDER BY u.first_name ASC
`

type GetContactsRow struct {
	ContactID   pgtype.UUID `json:"contact_id"`
	FirstName   pgtype.Text `json:"first_name"`
	SecondName  pgtype.Text `json:"second_name"`
	PhoneNumber string      `json:"phone_number"`
	Image       pgtype.Text `json:"image"`
}

func (q *Queries) GetContacts(ctx context.Context, userID pgtype.UUID) ([]GetContactsRow, error) {
	rows, err := q.db.Query(ctx, getContacts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetContactsRow{}
	for rows.Next() {
		var i GetContactsRow
		if err := rows.Scan(
			&i.ContactID,
			&i.FirstName,
			&i.SecondName,
			&i.PhoneNumber,
			&i.Image,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
