// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getMessages = `-- name: GetMessages :many
SELECT m.id, m.content, m.sender_id, m.conversation_id, m.created_at
FROM messages m
WHERE m.conversation_id = $1
ORDER BY m.created_at ASC
`

type GetMessagesRow struct {
	ID             pgtype.UUID      `json:"id"`
	Content        pgtype.Text      `json:"content"`
	SenderID       pgtype.UUID      `json:"sender_id"`
	ConversationID pgtype.UUID      `json:"conversation_id"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) GetMessages(ctx context.Context, conversationID pgtype.UUID) ([]GetMessagesRow, error) {
	rows, err := q.db.Query(ctx, getMessages, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMessagesRow{}
	for rows.Next() {
		var i GetMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.SenderID,
			&i.ConversationID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveMessage = `-- name: SaveMessage :one
INSERT INTO messages (conversation_id, sender_id, content)
VALUES ($1, $2, $3)
RETURNING id, conversation_id, sender_id, content, created_at
`

type SaveMessageParams struct {
	ConversationID pgtype.UUID `json:"conversation_id"`
	SenderID       pgtype.UUID `json:"sender_id"`
	Content        pgtype.Text `json:"content"`
}

func (q *Queries) SaveMessage(ctx context.Context, arg SaveMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, saveMessage, arg.ConversationID, arg.SenderID, arg.Content)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SenderID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}
