// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Contact struct {
	ID        pgtype.UUID      `json:"id"`
	UserID    pgtype.UUID      `json:"user_id"`
	ContactID pgtype.UUID      `json:"contact_id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type Conversation struct {
	ID             pgtype.UUID      `json:"id"`
	ParticipantOne pgtype.UUID      `json:"participant_one"`
	ParticipantTwo pgtype.UUID      `json:"participant_two"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
}

type Message struct {
	ID             pgtype.UUID      `json:"id"`
	ConversationID pgtype.UUID      `json:"conversation_id"`
	SenderID       pgtype.UUID      `json:"sender_id"`
	Content        pgtype.Text      `json:"content"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
}

type User struct {
	ID          pgtype.UUID      `json:"id"`
	Username    string           `json:"username"`
	Password    string           `json:"password"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
	PhoneNumber string           `json:"phone_number"`
	DateOfBirth pgtype.Text      `json:"date_of_birth"`
	FirstName   pgtype.Text      `json:"first_name"`
	SecondName  pgtype.Text      `json:"second_name"`
	Image       pgtype.Text      `json:"image"`
}
