// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: conversations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createConversation = `-- name: CreateConversation :one
INSERT INTO conversations (participant_one, participant_two)
VALUES ($1, $2)
RETURNING id
`

type CreateConversationParams struct {
	ParticipantOne pgtype.UUID `json:"participant_one"`
	ParticipantTwo pgtype.UUID `json:"participant_two"`
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createConversation, arg.ParticipantOne, arg.ParticipantTwo)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const existingConversation = `-- name: ExistingConversation :one
SELECT id from conversations 
WHERE (participant_one = $1 AND participant_two = $2)
    OR (participant_one = $2 AND participant_two = $1)
LIMIT 1
`

type ExistingConversationParams struct {
	ParticipantOne pgtype.UUID `json:"participant_one"`
	ParticipantTwo pgtype.UUID `json:"participant_two"`
}

func (q *Queries) ExistingConversation(ctx context.Context, arg ExistingConversationParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, existingConversation, arg.ParticipantOne, arg.ParticipantTwo)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const fetchConversationsByUserId = `-- name: FetchConversationsByUserId :many
SELECT  
    c.id AS conversation_id,  

    (
        CASE  
            WHEN u1.id = $1 THEN u2.first_name  
            ELSE u1.first_name  
        END
    )::text AS participant_name,

    (
        CASE  
            WHEN u1.id = $1 THEN u2.second_name  
            ELSE u1.second_name  
        END
    )::text AS participant_surname,

    (
    COALESCE(
        CASE
            WHEN u1.id = $1 THEN u2.image
            ELSE u1.image
        END,
        ''
    )
)::text AS participant_image,

    m.content AS last_message,  
    m.created_at AS last_message_time  

FROM conversations c  
JOIN users u1 ON u1.id = c.participant_one  
JOIN users u2 ON u2.id = c.participant_two  
LEFT JOIN LATERAL (  
    SELECT content, created_at  
    FROM messages  
    WHERE conversation_id = c.id  
    ORDER BY created_at DESC  
    LIMIT 1  
) m ON true  
WHERE c.participant_one = $1 OR c.participant_two = $1  
ORDER BY m.created_at DESC
`

type FetchConversationsByUserIdRow struct {
	ConversationID     pgtype.UUID      `json:"conversation_id"`
	ParticipantName    string           `json:"participant_name"`
	ParticipantSurname string           `json:"participant_surname"`
	ParticipantImage   string           `json:"participant_image"`
	LastMessage        pgtype.Text      `json:"last_message"`
	LastMessageTime    pgtype.Timestamp `json:"last_message_time"`
}

func (q *Queries) FetchConversationsByUserId(ctx context.Context, id pgtype.UUID) ([]FetchConversationsByUserIdRow, error) {
	rows, err := q.db.Query(ctx, fetchConversationsByUserId, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FetchConversationsByUserIdRow{}
	for rows.Next() {
		var i FetchConversationsByUserIdRow
		if err := rows.Scan(
			&i.ConversationID,
			&i.ParticipantName,
			&i.ParticipantSurname,
			&i.ParticipantImage,
			&i.LastMessage,
			&i.LastMessageTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
