// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddContact(ctx context.Context, arg AddContactParams) error
	CreateConversation(ctx context.Context, arg CreateConversationParams) (pgtype.UUID, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	ExistingConversation(ctx context.Context, arg ExistingConversationParams) (pgtype.UUID, error)
	FetchConversationsByUserId(ctx context.Context, id pgtype.UUID) ([]FetchConversationsByUserIdRow, error)
	GetContacts(ctx context.Context, userID pgtype.UUID) ([]GetContactsRow, error)
	GetMessages(ctx context.Context, conversationID pgtype.UUID) ([]GetMessagesRow, error)
	GetUserByPhone(ctx context.Context, phoneNumber string) (User, error)
	SaveMessage(ctx context.Context, arg SaveMessageParams) (Message, error)
}

var _ Querier = (*Queries)(nil)
