// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, phone_number, password, first_name, second_name)
VALUES ($1, $2, $3, $4, $5) 
RETURNING id, username, password, created_at, updated_at, phone_number, date_of_birth, first_name, second_name, image
`

type CreateUserParams struct {
	Username    string      `json:"username"`
	PhoneNumber string      `json:"phone_number"`
	Password    string      `json:"password"`
	FirstName   pgtype.Text `json:"first_name"`
	SecondName  pgtype.Text `json:"second_name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.PhoneNumber,
		arg.Password,
		arg.FirstName,
		arg.SecondName,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PhoneNumber,
		&i.DateOfBirth,
		&i.FirstName,
		&i.SecondName,
		&i.Image,
	)
	return i, err
}

const getUserByPhone = `-- name: GetUserByPhone :one
SELECT id, username, password, created_at, updated_at, phone_number, date_of_birth, first_name, second_name, image FROM users 
WHERE phone_number = $1
`

func (q *Queries) GetUserByPhone(ctx context.Context, phoneNumber string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByPhone, phoneNumber)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PhoneNumber,
		&i.DateOfBirth,
		&i.FirstName,
		&i.SecondName,
		&i.Image,
	)
	return i, err
}
